import type { Metadata } from "next";
import { Cinzel, Cinzel_Decorative, Marcellus, Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import Header from "@/shared/layout/Header";
import Footer from "@/shared/layout/Footer";


const cinzel = Cinzel({
  variable:"--font-headings",
  subsets:["latin"]
})

const cinzelDecorative = Cinzel_Decorative({
  variable:"--font-display",
  weight: "400",
  subsets:["latin"]
})
const marcellus = Marcellus({
  variable:"--font-ui",
  weight: "400",
  subsets:["latin"]
})
const cormorantGaramond = Cormorant_Garamond({
  variable:"--font-body",
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-dvh relative ${cinzel.variable} ${cinzelDecorative.variable} ${marcellus.variable} ${cormorantGaramond.variable}  antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
