import type { Metadata } from "next";
import {
  Cinzel,
  Cinzel_Decorative,
  Marcellus,
  Cormorant_Garamond,
} from "next/font/google";
import "./globals.css";
import Header from "@/shared/layout/Header";
import Footer from "@/shared/layout/Footer";
import Provider from "@/shared/layout/Provider";

const cinzelDecorative = Cinzel_Decorative({
  variable: "--font-display",
  weight: "400",
  subsets: ["latin"],
});
const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-body",
  subsets: ["latin"],
});

const cinzel = Cinzel({
  variable: "--font-titles",
  subsets: ["latin"],
});
const marcellus = Marcellus({
  variable: "--font-ui",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Connect Latam VT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${cinzel.variable} ${cinzelDecorative.variable} ${marcellus.variable} ${cormorantGaramond.variable}  antialiased`}
      >
        <Provider>
          <div className="flex flex-col h-dvh">
            <Header />
            <main className="flex-1 overflow-y-auto">
              {children}
            </main>
            <Footer />
          </div>
        </Provider>
      </body>
    </html>
  );
}
